/*
 * Copyright (c) 2003-2005 <a href="http://jggapi.sourceforge.net/team-list.html">JGGApi Development Team</a> All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
package pl.mn.communicator;

import java.util.Date;

import pl.mn.communicator.packet.GGUtils;

/**
 * The message that is received from Gadu-Gadu server.
 * <p>
 * Created on 2004-11-21
 * 
 * @author <a href="mailto:mati@sz.home.pl">Mateusz Szczap</a>
 * @version $Id: IncomingMessage.java,v 1.4 2004-12-19 18:50:43 winnetou25 Exp $
 */
public class IncomingMessage extends AbstractMessage {

	/** The time the message was sent */
	private Date m_messageDate = null;
	
	/** The unique messageID that is set by client to identify message */
	private int m_messageID = -1;
	
    /**
     * 
	 * @param uin Gadu-Gadu number of the user that sent the message.
	 * @param messageBody
	 * @throws IllegalArgumentException if the uin or messageID or messageDate is a negative value.
	 * @throws NullPointerException if the messageBody is null.
	 */
	public IncomingMessage(int uin, String messageBody, int messageID, long messageDate, int protocolMessageClass) {
		super(uin, messageBody, GGUtils.getClientMessageClass(protocolMessageClass));
		if (messageDate < 0) throw new IllegalArgumentException("messageDate cannot be less than 0");
		if (messageID < 0) throw new IllegalArgumentException("messageID cannot be less than 0");
		m_messageDate = new Date(messageDate);
		m_messageID = messageID;
	}
	
	/**
	 * Returns the unique message id that was generated by client.
	 * @return int the unique message id previously generated on client side.
	 */
	public int getMessageID() {
		return m_messageID;
	}

	/**
	 * Returns the time this message was sent.
	 * @return Date the time this message was sent.
	 */
    public Date getMessageDate() {
    	return m_messageDate;
    }
    
}
